micronaut:
  application:
    name: freteRest

## configs para o channel do cliente gRPC
grpc:
  client:
    plaintext: true # não deve ser utilizado em produção
    max-retry-attempts: 10
  channels:
    frete:
      address: 'localhost:50051' # endereço onde está rodando o servidor gRPC desse serviço
      plaintext: true
      max-retry-attempts: 10